name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and run services
      run: |
        docker-compose up --build -d
        sleep 10 # wait for services to start

    - name: Test Microservice 1 Health Check
      run: curl --fail http://localhost:3001/check

    - name: Test Microservice 2 Health Check
      run: curl --fail http://localhost:3002/check

    - name: Test Microservice 3 Health Check
      run: curl --fail http://localhost:3003/check

    - name: Test Microservice 4 Health Check
      run: curl --fail http://localhost:3004/check
