name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Deploy to Hetzner server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        #port: 22
        script: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          systemctl restart docker
          
          docker stop microservice-1
          docker rm microservice-1
          docker rmi -f microservice-1
          
          docker stop microservice-2
          docker rm microservice-2
          docker rmi -f microservice-2
          
          docker stop microservice-3
          docker rm microservice-3
          docker rmi -f microservice -3
          
          docker stop microservice-4
          docker rm microservice-4
          docker rmi -f microservice-4
          
          
          cd /root/micro
          docker compose down
          docker compose pull
          git pull origin
          docker compose up -d --build

          docker image prune -af
    




    

   
